### ISSUE TITLE
this directRequest happen for all directrequest

### ISSUE THREAD

**Issue by Shnoulle** [olleharstedt/MassAction#1]
In https://github.com/olleharstedt/MassAction/blob/master/MassAction.php#L229

newDirectRequest function : you must test if target is the plugin : else it happen for all directRequest (and broke other plugins ;)

I make the pull request when i found time to test plugin

**Comment by olleharstedt** [comment]
_Why_ does it fire all plugins? Direct request always includes plugin name.

**Comment by Shnoulle** [comment]
Don't know . There are some reason before where it can needed : for example "plugin deactuvate all directRequest". But now : we have a global plugin event for all request. Then no reason to sent to all plugin.

BUT : with this plugin/last GIT ls version : you broke ALL directRequest of All other plugin :)

**Comment by olleharstedt** [comment]
OK, what's the fix (in my code)? Check so plugin name is "MassAction"?

**Comment by Shnoulle** [comment]
https://github.com/olleharstedt/MassAction/pull/2
