### ISSUE TITLE
Advanced question settings

### ISSUE THREAD

**Issue by tpartner** [olleharstedt/MassAction#12]
Thanks Olle, great plugin.

A "nice to have" would be the advanced question settings like question validation or slider settings.

**Comment by olleharstedt** [comment]
Yeah, I've added a couple of those. Just list the ones you need and I'll add them.

**Comment by tpartner** [comment]
I think these would apply to many question types:
- Random order
- Hide tip
- Always hide this question
- Minimum answers
- Maximum answers
- Array filter
- Array filter exclusion
- Question validation equation
- Question validation tip
- Sub-question validation equation
- Sub-question validation tip

These may be a little too question-type specific:
- Label for 'Other:' option
- Minimum value
- Maximum value
- Equals sum value
- Minimum sum value
- Maximum sum value
- Exclusive option
- Slider settings

**Comment by olleharstedt** [comment]
Won't add tip, since it's localized.

**Comment by olleharstedt** [comment]
Please do a pull requestion for the second list of attributes, or provide me with a list of question types that apply to them, or, better still, the attribute names as they are in the database.
