### ISSUE TITLE
Server error in 2.06 LTS

### ISSUE THREAD

**Issue by tpartner** [olleharstedt/MassAction#13]
Hi Olle, 

I get the following error in 2.06:

 - Fatal error: Call to undefined method MassAction::renderPartial() in C:\xampp\htdocs\limeSurvey206\plugins\MassAction\MassAction.php on line 173

Environment:
- LS 2.06 LTS, (Git pull 01/11/16)
- Firefox or Chrome
- PHP Version 5.5.19
- Apache/2.4.10 (Win32)
- mysql 5.0.11

**Comment by olleharstedt** [comment]
OK, will check.

**Comment by olleharstedt** [comment]
Fixed, but everything else seems broken in 2.06.
