### ISSUE TITLE
Items are shown in wrong order

### ISSUE THREAD

**Issue by maziminke** [olleharstedt/MassAction#14]
When loading the group or question details, the data seems to be ordered by group or question ID. This is a little confusing since the order within a survey can be totally different (groups being moved around, questions which were added later, ...).
Especially for larger surveys outputting the data ordered by the sequence they are shown at the survey will help a ,lot finding the proper item you want to edit.

**Comment by olleharstedt** [comment]
Noted. So people still use this extension?

**Comment by maziminke** [comment]
Sure, I am also spreading it at some companies doing lots of surveys.

**Comment by trivender** [comment]
I agree with maziminke.

**Comment by Deusdeorum** [comment]
This plugin makes life in LS much more easier, sure you can export and import and stuff, but mass editing a wrong condition that is set on multiple places is a great feature. And I see that you made some pushes and working on it for 4.x but do you have plans on releasing it to 3.x? 

"So people still use this extension?" YES. Everyone should use it. Should be in core!!! :)

**Comment by alexmarketaccess** [comment]
Is there even an LS 4.x?

**Comment by olleharstedt** [comment]
LS4 is the dev branch. MassAction plugin will be part of the extension shop prototype ("LimeShop").

If it works on 4.0.0dev it "should" work on LS3. I can look into it.

**Comment by Deusdeorum** [comment]
"Call to undefined method LimeSurvey\PluginManager\LimesurveyApi::renderTwig()" for LS 3.7.3

**Comment by olleharstedt** [comment]
Ah, crap.

**Comment by olleharstedt** [comment]
I pushed some fixes to LimeSurvey master. Please try again with LS 3.10.0 when released.

**Comment by maziminke** [comment]
_"MassAction plugin will be part of the extension shop prototype ("LimeShop")"_
-> Does that mean that users will have to pay for future versions?

**Comment by olleharstedt** [comment]
@maziminke No, it will a free plugin. The idea was that "LimeShop" could be used to distribute all kinds of content, not only paid.
