### ISSUE TITLE
Class 'QuickMenuButton' not found

### ISSUE THREAD

**Issue by Shnoulle** [olleharstedt/MassAction#3]
Activate plugin
Go to survey
 Fatal error: Class 'QuickMenuButton' not found in /home/sondages.pro/htdocs/limesurvey_GIT/LimeSurvey/plugins/MassAction/MassAction.php on line 135

It's easy to test if plugin is present and active when ativate (or before do something). Do you want a pull request or ?

**Comment by olleharstedt** [comment]
Well, this is why I wanted to implement configuration files... Do you have a code snippet? Or just check if the class is defined?

**Comment by Shnoulle** [comment]
No, when activate : just check if plugin is active.
Something like that:
`if(!Plugin::model()->find("name='otherPlugin' and active=1")){ ....`

BUT : 
- Have a clean way to display something in admin GUI with menu etc ... must be in core . See https://github.com/Shnoulle/LS-extendRemoteControl/blob/master/extendRemoteControl.php#L95

**Comment by olleharstedt** [comment]
OK, seems simple enough. Will add later.

**Comment by Shnoulle** [comment]
Yes: but 
- Have a clean way for plugin to add display content on admin OR public
- Have a clean way to extend menu

Is a must have in core, no ?

**Comment by olleharstedt** [comment]
For 1), it's now pretty easy to add content in admin in 2.5, as I did in mass action.

For 2), it's possible to add menu items to top bar and to tools menu. Quick-menu is not part of core, so...Maybe I should add an extra event that fired from quick-menu plugin, for other plugins to add buttons to quick-menu (better than current solution in mass action).

**Comment by Shnoulle** [comment]
For 1 : i try 
- $oAdminController->render('application.views.admin.remotecontrol.index_view',$aData);
- Yii::app()->getController()->render('application.views.admin.remotecontrol.index_view',$aData);

in https://github.com/Shnoulle/LS-extendRemoteControl/blob/master/extendRemoteControl.php#L95

[edit] 1 not 2
It's because i want to use an included views ? Can you help me on that ?

**Comment by olleharstedt** [comment]
No problem, text me on the IRC.

**Comment by olleharstedt** [comment]
Or here: You need to return the string instead of echo it.

**Comment by olleharstedt** [comment]
You don't have to get the admin header, I think.

``` php
$content = App()->getController()->renderPartial('application.views.admin.remotecontrol.index_view',$aData, true);
return $content
```

(Notice `true` at end of renderpartial().)

https://github.com/olleharstedt/MassAction/blob/master/MassAction.php#L98

**Comment by olleharstedt** [comment]
Hm, maybe `setContent` is better than return content...

**Comment by Shnoulle** [comment]
I use echo : because in MassAction you use:
`echo $this->$functionToCall($request);`
And in $functionToCall you return $content.

You're right for the true. I test it.

**Comment by olleharstedt** [comment]
Oh, right! Sorry.

**Comment by olleharstedt** [comment]
Then it should work. What output do you get when you call the plugin action?

**Comment by olleharstedt** [comment]
(`true` is only when render should return a string, shouldn't make a difference here.)

**Comment by Shnoulle** [comment]
The original bug was fixed since QUickMenu is added :). 
The answer of the question is here  https://github.com/Shnoulle/LS-extendRemoteControl/commit/637af7f73a5859a988e55fd10bd0488ca20a0180#diff-78c83f6f27d7f8e4250a60dbd180ecb6R121 : different url : no directRequestEvent :) .

I update layout to take really a default layout for directRequest : without menu or anything else.

**Comment by olleharstedt** [comment]
Oh yeah, I added that controller. Sorry, should've thought of it. Glad it worked out.
